// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPUJy7vTdudV3s4UdNcesHyEHGqXuLUk',
    appId: '1:759698882835:web:82e8f5736376b51461dae6',
    messagingSenderId: '759698882835',
    projectId: 'sowaste-16615',
    authDomain: 'sowaste-16615.firebaseapp.com',
    storageBucket: 'sowaste-16615.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHamc6Mah9AMPdN-FYb3I7GF6G7RT-C4',
    appId: '1:759698882835:android:ce23b4efa1a52ff961dae6',
    messagingSenderId: '759698882835',
    projectId: 'sowaste-16615',
    storageBucket: 'sowaste-16615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46QUF2sXI3rweEceFjliV8pvJiCxM0ag',
    appId: '1:759698882835:ios:e9b348fd812eef4f61dae6',
    messagingSenderId: '759698882835',
    projectId: 'sowaste-16615',
    storageBucket: 'sowaste-16615.appspot.com',
    androidClientId:
        '759698882835-qtdo0flh0dbvjilhfi0lcmseefgdq47u.apps.googleusercontent.com',
    iosClientId:
        '759698882835-tdglbsq2jrvl4dqjtb253h66b1idskh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sowaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA46QUF2sXI3rweEceFjliV8pvJiCxM0ag',
    appId: '1:759698882835:ios:e9b348fd812eef4f61dae6',
    messagingSenderId: '759698882835',
    projectId: 'sowaste-16615',
    storageBucket: 'sowaste-16615.appspot.com',
    androidClientId:
        '759698882835-qtdo0flh0dbvjilhfi0lcmseefgdq47u.apps.googleusercontent.com',
    iosClientId:
        '759698882835-tdglbsq2jrvl4dqjtb253h66b1idskh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.sowaste',
  );
}
